// <auto-generated />
using BookProject.Web.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookProject.Web.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookProject.Web.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "James Patterson",
                            Genre = "Biography",
                            ISBN = "359-0-9921-2413-7",
                            Title = "Thief Of The South"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Sci-fi",
                            ISBN = "823-0-5471-0259-1",
                            Title = "Titan Retreating"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Oscar Wilde",
                            Genre = "Romance",
                            ISBN = "487-0-6398-9010-8",
                            Title = "He Stole My Knight"
                        },
                        new
                        {
                            Id = 4,
                            Author = "James Joyce",
                            Genre = "Mystery",
                            ISBN = "143-0-2581-2591-4",
                            Title = "Rescue At The Castle"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Ernest Hemingway",
                            Genre = "Crime",
                            ISBN = "561-0-1795-1795-8",
                            Title = "Made for Duty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
